Repository WithTime12/WithTimeBE, pull requests merged in 2025-08, with the labels that each got.

#73 🐛 [Fix] Cors 해결
  src/main/java/org/withtime/be/withtimebe/global/data/CorsConfigData.java
  src/main/java/org/withtime/be/withtimebe/global/security/SecurityConfig.java
  src/main/resources/application-develop.yml
  src/main/resources/application.yml
Labels: 🐛 fix

#74 🐛 [Fix] 데이트 취향 테스트 일부 로직 및 Swagger 문서 수정
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/controller/DatePreferenceController.java
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/util/WeightBaseTestScoreCalculator.java
Labels: 🐛 fix

#75 🐛 [Fix] Cors 서버 배포 주소 추가
  src/main/resources/application-develop.yml
Labels: 🐛 fix

#81 ✨ [Feat] 로그인 사용자가 설정한 지역 조회 API, 사용자 지역 변경 API
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Member.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/controller/RegionController.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/controller/WeatherController.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/converter/RegionConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/dto/request/RegionReqDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/dto/response/RegionResDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/service/command/RegionCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/service/command/RegionCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/service/query/RegionQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/service/query/RegionQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/RegionErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/exception/RegionException.java
Labels: ✨feature

#70 ✨ [Feat] 회원 등급 조회 API 및 포인트 적립 AOP 구현
  src/main/java/org/withtime/be/withtimebe/domain/log/datecourselog/controller/DateCourseLogQueryController.java
  src/main/java/org/withtime/be/withtimebe/domain/member/annotation/GetPoint.java
  src/main/java/org/withtime/be/withtimebe/domain/member/annotation/enums/PointAction.java
  src/main/java/org/withtime/be/withtimebe/domain/member/aop/GetPointAspect.java
  src/main/java/org/withtime/be/withtimebe/domain/member/controller/GradeController.java
  src/main/java/org/withtime/be/withtimebe/domain/member/controller/MemberController.java
  src/main/java/org/withtime/be/withtimebe/domain/member/converter/GradeConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/member/dto/GradeResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/member/dto/MemberResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Grade.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Member.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/enums/GradeType.java
  src/main/java/org/withtime/be/withtimebe/domain/member/repository/GradeRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/command/MemberCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/query/GradeQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/query/GradeQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/GradeErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/exception/GradeException.java
Labels: ✨feature

#78 ♻️ [REFACTOR] 레디스 캐싱을 통한 인기 키워드 조회 성능 개선
  build.gradle
  src/main/java/org/withtime/be/withtimebe/WithTimeBeApplication.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/scheduler/PlaceCategoryLogScheduler.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/service/query/PlaceCategoryLogQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/config/MapperConfig.java
  src/main/java/org/withtime/be/withtimebe/global/config/RedisConfig.java
Labels: ♻️ refactor

#83 🐛[FIX] ObjectMapper로 인한 response 오류 수정
  src/main/java/org/withtime/be/withtimebe/global/config/MapperConfig.java
  src/main/java/org/withtime/be/withtimebe/global/config/RedisConfig.java
Labels: 🐛 fix

#85 🐛 [FIX] Grade 조회 로직 수정
  src/main/java/org/withtime/be/withtimebe/domain/member/repository/GradeRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/query/GradeQueryServiceImpl.java
Labels: 🐛 fix

#88 ✨ [Feat] 잘 맞는 유형, 안 맞는 유형 검색 API 구현
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/controller/DatePreferenceController.java
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/converter/DatePreferenceConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/dto/DatePreferenceResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/entity/DatePreferenceTypeRelation.java
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/entity/enums/PreferenceRelationType.java
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/repository/DatePreferenceTypeRelationRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/service/query/DatePreferenceTypeRelationQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/service/query/DatePreferenceTypeRelationQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/util/WeightBaseTestScoreCalculator.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/DatePreferenceErrorCode.java
Labels: ✨feature

#103 ✨ [FEAT] 사용자 행동 별 포인트 적립 및 인기 키워드 집계 AOP 적용
  src/main/java/org/withtime/be/withtimebe/domain/date/preference/service/command/DatePreferenceTestCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/date/service/command/DateCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/date/service/query/DateQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/aop/LogPlaceCategoryAspect.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/converter/PlaceCategoryLogConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/model/PlaceCategoryLog.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/repository/PlaceCategoryLogRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/scheduler/PlaceCategoryLogScheduler.java
  src/main/java/org/withtime/be/withtimebe/domain/member/aop/GetPointAspect.java
Labels: ✨feature

#113 🐛 [Fix] 사용자 탈퇴 시 로그아웃 되도록 수정
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/member/controller/MemberController.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/command/MemberCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/security/handler/CustomLogoutHandler.java
Labels: 🐛 fix

#116 🐛 [Fix] 토큰 없는 경우 400으로 에러 처리
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/TokenErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/security/handler/CustomLogoutHandler.java
Labels: 🐛 fix
