Repository WithTime12/WithTimeBE, pull requests merged in 2025-07, with the labels that each got.

#10 🚀 [Chore] swagger 세팅
  build.gradle
  src/main/java/org/withtime/be/withtimebe/global/common/HealthCheckController.java
  src/main/java/org/withtime/be/withtimebe/global/config/SwaggerConfig.java
  src/main/java/org/withtime/be/withtimebe/global/security/SecurityConfig.java
Labels: 🚀 chore

#9 :rocket: [Chore] cicd 세팅
  .github/workflows/dev_deploy.yml
  Dockerfile
  build.gradle
Labels: 🚀 chore, 👷 ci

#6 🚀 [Chore] entity setting
  src/main/java/org/withtime/be/withtimebe/domain/auth/dto/request/AuthRequestDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/dto/response/AuthResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/BusinessTime.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/DateCourse.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/DatePlace.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/DatePlaceDateCourse.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/DatePlacePlaceCategory.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/Item.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/MemberPlaceCategory.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/PlaceCategory.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/Review.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/enums/Day.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/enums/PlaceCategoryPriority.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/enums/PlaceCategoryType.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Alarm.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Member.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Payments.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Social.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/enums/AlarmType.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/enums/BillingStatus.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/enums/Role.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/enums/SocialType.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/enums/UserRank.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/entity/Notice.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/entity/enums/NoticeCategory.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/DailyRecommendation.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/Keyword.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/RawMediumTermWeather.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/RawShortTermWeather.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/Region.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/TemplateKeyword.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/WeatherTemplate.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/enums/PrecipCategory.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/enums/TempCategory.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/enums/Weather.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🚀 chore

#14 🐛 [Fix] 기존 로그인 방식 쿠키로 변경
  src/main/java/org/withtime/be/withtimebe/domain/auth/controller/AuthController.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/JwtTokenQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/TokenQueryService.java
  src/main/java/org/withtime/be/withtimebe/global/security/constants/AuthenticationConstants.java
  src/main/java/org/withtime/be/withtimebe/global/security/filter/JwtFilter.java
  src/main/java/org/withtime/be/withtimebe/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/org/withtime/be/withtimebe/global/util/CookieUtil.java
  src/main/java/org/withtime/be/withtimebe/global/util/JwtUtil.java
Labels: 🐛 fix

#25 🚀 [Chore] DatePlace 관련 엔티티 재설계 및 ERD 수정
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/DatePlace.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/DatePlacePlaceCategory.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/PlaceCategory.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/enums/PlaceCategoryPriority.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/enums/PlaceCategoryType.java
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/enums/PlaceType.java
Labels: 🚀 chore

#28 ✨ [Feat] No Resource Error 400으로 처리하기
  src/main/java/org/withtime/be/withtimebe/global/error/ExceptionAdviceConfig.java
  src/main/java/org/withtime/be/withtimebe/global/error/NoResourceFoundExceptionHandler.java
Labels: ✨feature

#33 🐛 [Fix] 프론트 로컬 환경 Cors 설정
  src/main/java/org/withtime/be/withtimebe/global/security/SecurityConfig.java
Labels: 🐛 fix

#19 ✨ [Feat] 공지사항 관련 API 구현
  src/main/java/org/withtime/be/withtimebe/domain/notice/controller/command/NoticeCommandController.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/controller/query/NoticeQueryController.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/converter/NoticeConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/dto/request/NoticeRequestDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/dto/response/NoticeResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/entity/Notice.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/repository/NoticeRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/service/command/NoticeCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/service/command/NoticeCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/service/query/NoticeQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/service/query/NoticeQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/annotation/SwaggerPageable.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/NoticeErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/exception/NoticeException.java
  src/main/java/org/withtime/be/withtimebe/global/security/SecurityConfig.java
  src/main/java/org/withtime/be/withtimebe/global/security/domain/CustomUserDetails.java
Labels: ✨feature

#36 :test_tube: [Test] 테스트 환경 추가
  build.gradle
  src/test/resources/application-test.yml
Labels: 🧪 test

#37 ✨ [Feat] 이메일 인증 로직 구현
  build.gradle
  src/main/java/org/withtime/be/withtimebe/domain/auth/constants/EmailVerificationStorageConstants.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/controller/AuthController.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/dto/request/EmailRequestDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/generator/RandomGenerator.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/generator/RandomSixDigitGenerator.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/EmailCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/EmailCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/EmailVerificationCodeStorageCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/RedisEmailVerificationCodeStorageCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/query/EmailVerificationCodeStorageQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/query/RedisEmailVerificationCodeStorageQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/util/MailVerificationCodeSender.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/util/SMTPMailVerificationCodeSender.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/EmailErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/exception/EmailException.java
  src/main/resources/application-develop.yml
  src/main/resources/application.yml
  src/main/resources/templates/email-verification.html
Labels: ✨feature

#41 ✨ [Feat] 자주 묻는 질문 API 구현
  src/main/java/org/withtime/be/withtimebe/domain/faq/controller/FaqCommandController.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/controller/FaqQueryController.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/converter/FaqCategoryConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/converter/FaqConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/dto/request/FaqRequestDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/dto/response/FaqResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/entity/Faq.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/entity/enums/FaqCategory.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/repository/FaqRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/service/command/FaqCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/service/command/FaqCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/service/query/FaqQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/faq/service/query/FaqQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/controller/command/NoticeCommandController.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/controller/query/NoticeQueryController.java
  src/main/java/org/withtime/be/withtimebe/domain/notice/entity/Notice.java
  src/main/java/org/withtime/be/withtimebe/global/annotation/SwaggerPageable.java
  src/main/java/org/withtime/be/withtimebe/global/config/WebConfig.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/FaqErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/exception/FaqException.java
  src/main/java/org/withtime/be/withtimebe/global/security/SecurityConfig.java
Labels: ✨feature, ♻️ refactor

#45 ✨ [Feat] 단기 예보, 중기 예보 데이터 수집 스케줄러 및 트리거 API
  build.gradle
  src/main/java/org/withtime/be/withtimebe/domain/weather/config/WeatherWebClientConfig.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/controller/RegionController.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/controller/WeatherController.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/converter/RegionConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/converter/WeatherSyncConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/data/scheduler/WeatherScheduler.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/data/service/WeatherApiClient.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/data/service/WeatherApiClientImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/data/service/WeatherDataCollectionService.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/data/service/WeatherDataCollectionServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/data/utils/WeatherDataHelper.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/data/utils/WeatherDataParser.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/dto/request/RegionReqDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/dto/request/WeatherSyncReqDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/dto/response/RegionResDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/dto/response/WeatherSyncResDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/RawMediumTermWeather.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/RawShortTermWeather.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/Region.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/entity/RegionCode.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/repository/RawMediumTermWeatherRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/repository/RawShortTermWeatherRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/repository/RegionCodeRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/repository/RegionRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/service/command/RegionCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/service/command/RegionCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/service/command/WeatherTriggerService.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/service/command/WeatherTriggerServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/service/query/RegionQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/weather/service/query/RegionQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/WeatherErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/exception/WeatherException.java
  src/main/java/org/withtime/be/withtimebe/global/security/SecurityConfig.java
  src/main/resources/application-develop.yml
  src/main/resources/application.yml
Labels: ✨feature, ♻️ refactor

#49 ✨ [Feat] 소셜 로그인 구현
  build.gradle
  src/main/java/org/withtime/be/withtimebe/domain/auth/controller/AuthController.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/controller/OAuth2Controller.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/converter/OAuth2Converter.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/dto/request/AuthRequestDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/dto/response/OAuth2ResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/factory/OAuth2UserLoader.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/factory/OAuth2UserLoaderFactory.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/factory/support/AbstractOAuth2UserLoader.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/factory/support/GoogleUserLoader.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/factory/support/KakaoUserLoader.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/factory/support/NaverUserLoader.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/factory/support/dto/GoogleOAuth2ResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/factory/support/dto/KakaoOAuth2ResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/factory/support/dto/NaverOAuth2ResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/OAuth2CommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/OAuth2CommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/member/converter/SocialConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Member.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Social.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/enums/ProviderType.java
  src/main/java/org/withtime/be/withtimebe/domain/member/repository/SocialRepository.java
  src/main/java/org/withtime/be/withtimebe/global/data/OAuth2ConfigData.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/OAuthErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/SocialErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/exception/OAuthException.java
  src/main/java/org/withtime/be/withtimebe/global/error/exception/SocialException.java
  src/main/java/org/withtime/be/withtimebe/global/security/SecurityConfig.java
  src/main/java/org/withtime/be/withtimebe/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/org/withtime/be/withtimebe/global/security/manager/CookieTokenManager.java
  src/main/java/org/withtime/be/withtimebe/global/security/manager/TokenManager.java
  src/main/resources/application-develop.yml
  src/main/resources/application.yml
Labels: ✨feature

#53 🏗️ [Build] API Payload 버전 변경
  build.gradle
  src/main/java/org/withtime/be/withtimebe/global/error/ExceptionAdviceConfig.java
  src/main/java/org/withtime/be/withtimebe/global/error/NoResourceFoundExceptionHandler.java
Labels: 🚀 chore

#55 🐛 [Fix] 소셜 로그인 시 비밀번호 입력 로직 수정
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/AuthErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/security/filter/JsonLoginFilter.java
  src/main/java/org/withtime/be/withtimebe/global/security/service/CustomUserDetailsService.java
Labels: 🐛 fix

#58 ✨ [Feat] 비밀번호 찾기, 변경 및 사용자 정보(사용자 이름) 변경 API 구현 & 회원 가입 오류 수정
  src/main/java/org/withtime/be/withtimebe/domain/auth/controller/AuthController.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/dto/request/AuthRequestDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/AuthCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/member/controller/MemberController.java
  src/main/java/org/withtime/be/withtimebe/domain/member/converter/MemberConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/member/dto/MemberRequestDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/member/dto/MemberResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Member.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/command/MemberCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/query/MemberQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/query/MemberQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/AuthErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/MemberErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/security/SecurityConfig.java
  src/main/java/org/withtime/be/withtimebe/global/security/filter/JwtFilter.java
Labels: ✨feature

#60 ✨ [Feat] 알림 구현
  build.gradle
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/factory/AlarmSenderFactory.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/firebase/FirebaseInitialization.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/generator/AlarmMessageGenerator.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/generator/EmailSMTPAlarmMessageGenerator.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/generator/FCMAlarmMessageGenerator.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/sender/AlarmSendUtil.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/sender/EmailSMTPAlarmSendUtil.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/sender/FCMAlarmSendUtil.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/service/AbstractAlarmSender.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/service/AlarmSender.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/service/EmailSMTPAlarmSender.java
  src/main/java/org/withtime/be/withtimebe/domain/member/alarm/service/FCMAlarmSender.java
  src/main/java/org/withtime/be/withtimebe/domain/member/controller/AlarmController.java
  src/main/java/org/withtime/be/withtimebe/domain/member/converter/AlarmConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/member/dto/AlarmRequestDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/member/dto/AlarmResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Alarm.java
  src/main/java/org/withtime/be/withtimebe/domain/member/entity/Member.java
  src/main/java/org/withtime/be/withtimebe/domain/member/repository/AlarmRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/AlarmCommandService.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/AlarmCommandServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/AlarmQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/member/service/AlarmQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/data/FirebaseConfigData.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/AlarmErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/code/FCMErrorCode.java
  src/main/java/org/withtime/be/withtimebe/global/error/exception/AlarmException.java
  src/main/java/org/withtime/be/withtimebe/global/error/exception/FCMException.java
  src/main/resources/application.yml
Labels: ✨feature

#61 ✨ [Feat] 월별 등록된 데이트 장소 수, 많이 찾은 키워드 집계, 테스트 코드 작성
  build.gradle
  src/main/java/org/withtime/be/withtimebe/WithTimeBeApplication.java
  src/main/java/org/withtime/be/withtimebe/domain/date/repository/DateCourseRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/date/repository/DatePlaceDateCourseRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/date/repository/DatePlaceRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/date/repository/PlaceCategoryRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/log/datecourselog/controller/DateCourseLogQueryController.java
  src/main/java/org/withtime/be/withtimebe/domain/log/datecourselog/converter/DateCourseLogConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/log/datecourselog/dto/DateCourseLogResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/log/datecourselog/service/query/DateCourseLogQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/log/datecourselog/service/query/DateCourseLogQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/log/dateplacelog/controller/DatePlaceLogQueryController.java
  src/main/java/org/withtime/be/withtimebe/domain/log/dateplacelog/converter/DatePlaceLogConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/log/dateplacelog/dto/DatePlaceLogResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/log/dateplacelog/entity/DatePlaceLog.java
  src/main/java/org/withtime/be/withtimebe/domain/log/dateplacelog/repository/DatePlaceLogRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/log/dateplacelog/scheduler/DatePlaceLogScheduler.java
  src/main/java/org/withtime/be/withtimebe/domain/log/dateplacelog/service/query/DatePlaceLogQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/log/dateplacelog/service/query/DatePlaceLogQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/annotation/LogPlaceCategory.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/aop/LogPlaceCategoryAspect.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/controller/PlaceCategoryLogQueryController.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/converter/PlaceCategoryLogConverter.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/dto/PlaceCategoryLogResponseDTO.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/model/PlaceCategoryLog.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/repository/PlaceCategoryLogRepository.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/scheduler/PlaceCategoryLogScheduler.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/service/query/PlaceCategoryLogQueryService.java
  src/main/java/org/withtime/be/withtimebe/domain/log/placecategorylog/service/query/PlaceCategoryLogQueryServiceImpl.java
  src/main/java/org/withtime/be/withtimebe/global/config/MongoConfig.java
  src/main/java/org/withtime/be/withtimebe/global/converter/MongoConverters.java
  src/main/java/org/withtime/be/withtimebe/global/security/SecurityConfig.java
  src/main/resources/application-develop.yml
  src/main/resources/application.yml
  src/test/java/org/withtime/be/withtimebe/domain/log/datecourselog/service/query/DateCourseLogQueryServiceImplTest.java
  src/test/java/org/withtime/be/withtimebe/domain/log/dateplacelog/service/query/DatePlaceLogQueryServiceImplTest.java
  src/test/java/org/withtime/be/withtimebe/domain/log/placecategorylog/aop/LogPlaceCategoryAspectTest.java
  src/test/java/org/withtime/be/withtimebe/domain/log/placecategorylog/service/query/PlaceCategoryLogQueryServiceImplTest.java
Labels: ✨feature

#63 🐛 [FIX] DateCourse 엔티티 BaseEntity 상속 누락 해결
  src/main/java/org/withtime/be/withtimebe/domain/date/entity/DateCourse.java
  src/main/java/org/withtime/be/withtimebe/global/security/SecurityConfig.java
Labels: 🐛 fix
